export const COLOR = {
  PRIMARY: '#4FB19D',
  SECONDARY: '#EDCE7A',

  LIGHT: '#FFFFFF',

  PRIMARY_TEXT: '#FFFFFF',
  TEXT_DARK: '#000000',

  BORDER_COLOR: '#DDDDDD',
  PLACEHOLDER: '#666666',
  BODY_BACKGROUND: '#DCDCDC',
};
